package br.usp.libras.sign.face;

public enum Chin {

    NADA, ESTUFADAS, NAO_ESTUFFADAS, SUGADAS, TENSAS, LINGUA_NA_BOCHECHA_DIREITA, 
    TODA_FACE_MOVE_PARA_DIREITA, SOPRANDO_AR, AR_DENTRO_DA_BOCA, EXPIRANDO, INSPIRANDO;
}
