package br.usp.libras.sign.face;

public enum Gaze {

    NADA, PARA_CIMA, PARA_CIMA_PARA_UM_LADO, PARA_OS_LADOS, PARA_BAIXO_PARA_UM_LADO,
    PARA_BAIXO, PARA_FRENTE, PARA_FRENTE_PARA_UM_LADO, PARA_OS_LADOS_2, PARA_TRAS_PARA_UM_LADO;
}
