package br.usp.libras.sign.face;

public enum Mounth {

    NADA, RETA_FECHADA,FECHADA_PARA_FRENTE, SORRISO_FECHADO, SORRISO_ABERTO, 
    METADE_SORRISO_METADE_RETA, TRISTE_FECHADA, TRISTE_ABERTA, ABERTA,
    ABERTA_PARA_FRENTE, ABERTA_FRANZIDA_AO_REDOR, OVAL_ABERTA, BOCEJO, 
    RETANGULAR_ABERTA_HORIZONTAL, RETANGULAR_ABERTA_VERTICAL, BEIJO, BEIJO_PROJETANDO,
    TENSA, TENSA_PARA_FRENTE, TENSA_PARA_TRAS, SUGADOS, LABIO_SUPERIOR_SOBRE_LABIO_INFERIOR,
    LABIO_INFERIOR_SOBRE_LABIO_SUPERIOR, UMA_DOBRA_AO_REDOR_DA_BOCA, DOBRAS_AO_REDOR_DA_BOCA,
    UMA_DOBRA_AO_REDOR_DO_LADO_DIREITO_DA_BOCA, DOBRAS_AO_REDOR_DO_LADO_DIREITO_DA_BOCA,
    LADO_DIREITO_ERGUIDO, AMBOS_LADOS_ERGUIDOS;
}
