package br.usp.libras.sign.face;

public enum Teeth {

    NADA, DENTES, SUPERIORES_TOCANDO_LABIO_INFERIOR, INFERIORES_TOCANDO_LABIO_SUPERIOR,
    SUPERIORES_TOCANDO_LINGUA, INFERIORES_TOCANDO_LINGUA, MORDIDA_CENTRO_DO_LABIO,
    MORDIDA_LADO_ESQUERDO_DO_LABIO;
}
