package br.usp.libras.sign.face;

public enum Tongue {

    NADA, PARA_CIMA_ABERTA, VISIVEL_DENTRO_DA_BOCA_PARA_BAIXO, METADE_PARA_CIMA_COM_BOCA_FECHADA,
    VISIVEL_DENTRO_DA_BOCA_PARA_CIMA, PARA_FORA_NO_CENTRO, VISIVEL_DENTRO_DA_BOCA_NO_CENTRO;
    
}
